[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@thirdweb-dev/=node_modules/@thirdweb-dev/',
    '@anon-aadhaar/=node_modules/@anon-aadhaar',
    '@openzeppelin/=node_modules/@openzeppelin'
]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config